### ISSUE TITLE
教室のレイアウト作成

### ISSUE THREAD

**Issue by EmiHasegawa0125** [Taito-Code/Remote-Class#4]

**Comment by taitotnk** [comment]
背景は白か青ベースでHeaderも作成したい

**Comment by taitotnk** [comment]
【TODO】
https://kitaharamugiro.github.io/Realtimely/jp/docs/api-guide/useRealtimeCursor/
Realtimelyをupdateしていただいたため、アバターを修正する

**Comment by taitotnk** [comment]
いい感じにできた！！
![image](https://user-images.githubusercontent.com/70618595/144259514-1fddf872-4187-465a-b95e-83f498573602.png)

あとはusernameも表示したい.
